/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappAiRouteImport } from './routes/whatsapp-ai'
import { Route as ReturRouteImport } from './routes/retur'
import { Route as PenjualanRouteImport } from './routes/penjualan'
import { Route as PengeluaranPribadiRouteImport } from './routes/pengeluaran-pribadi'
import { Route as PengeluaranRouteImport } from './routes/pengeluaran'
import { Route as MetaCommentsRouteImport } from './routes/meta-comments'
import { Route as MetaAdsRouteImport } from './routes/meta-ads'
import { Route as KeuanganRouteImport } from './routes/keuangan'
import { Route as ImportRiwayatRouteImport } from './routes/import-riwayat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StokPindahWadahRouteImport } from './routes/stok.pindah-wadah'
import { Route as StokKemasanRouteImport } from './routes/stok.kemasan'
import { Route as StokBahanBakuRouteImport } from './routes/stok.bahan-baku'
import { Route as PengaturanWhatsappRouteImport } from './routes/pengaturan.whatsapp'
import { Route as PengaturanStafRouteImport } from './routes/pengaturan.staf'
import { Route as PengaturanProfilRouteImport } from './routes/pengaturan.profil'
import { Route as PengaturanLumpsumRouteImport } from './routes/pengaturan.lumpsum'
import { Route as PengaturanHargaRouteImport } from './routes/pengaturan.harga'
import { Route as ApiWahaProxyRouteImport } from './routes/api.waha-proxy'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api.telegram-webhook'
import { Route as ApiWebhooksWhatsappRouteImport } from './routes/api.webhooks.whatsapp'
import { Route as ApiWebhooksMetaCommentsRouteImport } from './routes/api.webhooks.meta-comments'
import { Route as ApiMetaSyncCommentsRouteImport } from './routes/api.meta.sync-comments'
import { Route as ApiMetaSubscribePageRouteImport } from './routes/api.meta.subscribe-page'
import { Route as ApiMetaReplyCommentRouteImport } from './routes/api.meta.reply-comment'
import { Route as ApiMetaReplyAllUnrepliedRouteImport } from './routes/api.meta.reply-all-unreplied'
import { Route as ApiCronSyncMetaAdsRouteImport } from './routes/api.cron.sync-meta-ads'
import { Route as ApiCronSendResiRouteImport } from './routes/api.cron.send-resi'

const WhatsappAiRoute = WhatsappAiRouteImport.update({
  id: '/whatsapp-ai',
  path: '/whatsapp-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturRoute = ReturRouteImport.update({
  id: '/retur',
  path: '/retur',
  getParentRoute: () => rootRouteImport,
} as any)
const PenjualanRoute = PenjualanRouteImport.update({
  id: '/penjualan',
  path: '/penjualan',
  getParentRoute: () => rootRouteImport,
} as any)
const PengeluaranPribadiRoute = PengeluaranPribadiRouteImport.update({
  id: '/pengeluaran-pribadi',
  path: '/pengeluaran-pribadi',
  getParentRoute: () => rootRouteImport,
} as any)
const PengeluaranRoute = PengeluaranRouteImport.update({
  id: '/pengeluaran',
  path: '/pengeluaran',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaCommentsRoute = MetaCommentsRouteImport.update({
  id: '/meta-comments',
  path: '/meta-comments',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaAdsRoute = MetaAdsRouteImport.update({
  id: '/meta-ads',
  path: '/meta-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganRoute = KeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRiwayatRoute = ImportRiwayatRouteImport.update({
  id: '/import-riwayat',
  path: '/import-riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StokPindahWadahRoute = StokPindahWadahRouteImport.update({
  id: '/stok/pindah-wadah',
  path: '/stok/pindah-wadah',
  getParentRoute: () => rootRouteImport,
} as any)
const StokKemasanRoute = StokKemasanRouteImport.update({
  id: '/stok/kemasan',
  path: '/stok/kemasan',
  getParentRoute: () => rootRouteImport,
} as any)
const StokBahanBakuRoute = StokBahanBakuRouteImport.update({
  id: '/stok/bahan-baku',
  path: '/stok/bahan-baku',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanWhatsappRoute = PengaturanWhatsappRouteImport.update({
  id: '/pengaturan/whatsapp',
  path: '/pengaturan/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanStafRoute = PengaturanStafRouteImport.update({
  id: '/pengaturan/staf',
  path: '/pengaturan/staf',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanProfilRoute = PengaturanProfilRouteImport.update({
  id: '/pengaturan/profil',
  path: '/pengaturan/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanLumpsumRoute = PengaturanLumpsumRouteImport.update({
  id: '/pengaturan/lumpsum',
  path: '/pengaturan/lumpsum',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanHargaRoute = PengaturanHargaRouteImport.update({
  id: '/pengaturan/harga',
  path: '/pengaturan/harga',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWahaProxyRoute = ApiWahaProxyRouteImport.update({
  id: '/api/waha-proxy',
  path: '/api/waha-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram-webhook',
  path: '/api/telegram-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksWhatsappRoute = ApiWebhooksWhatsappRouteImport.update({
  id: '/api/webhooks/whatsapp',
  path: '/api/webhooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMetaCommentsRoute = ApiWebhooksMetaCommentsRouteImport.update({
  id: '/api/webhooks/meta-comments',
  path: '/api/webhooks/meta-comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaSyncCommentsRoute = ApiMetaSyncCommentsRouteImport.update({
  id: '/api/meta/sync-comments',
  path: '/api/meta/sync-comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaSubscribePageRoute = ApiMetaSubscribePageRouteImport.update({
  id: '/api/meta/subscribe-page',
  path: '/api/meta/subscribe-page',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaReplyCommentRoute = ApiMetaReplyCommentRouteImport.update({
  id: '/api/meta/reply-comment',
  path: '/api/meta/reply-comment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaReplyAllUnrepliedRoute =
  ApiMetaReplyAllUnrepliedRouteImport.update({
    id: '/api/meta/reply-all-unreplied',
    path: '/api/meta/reply-all-unreplied',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronSyncMetaAdsRoute = ApiCronSyncMetaAdsRouteImport.update({
  id: '/api/cron/sync-meta-ads',
  path: '/api/cron/sync-meta-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSendResiRoute = ApiCronSendResiRouteImport.update({
  id: '/api/cron/send-resi',
  path: '/api/cron/send-resi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/import-riwayat': typeof ImportRiwayatRoute
  '/keuangan': typeof KeuanganRoute
  '/meta-ads': typeof MetaAdsRoute
  '/meta-comments': typeof MetaCommentsRoute
  '/pengeluaran': typeof PengeluaranRoute
  '/pengeluaran-pribadi': typeof PengeluaranPribadiRoute
  '/penjualan': typeof PenjualanRoute
  '/retur': typeof ReturRoute
  '/whatsapp-ai': typeof WhatsappAiRoute
  '/api/telegram-webhook': typeof ApiTelegramWebhookRoute
  '/api/waha-proxy': typeof ApiWahaProxyRoute
  '/pengaturan/harga': typeof PengaturanHargaRoute
  '/pengaturan/lumpsum': typeof PengaturanLumpsumRoute
  '/pengaturan/profil': typeof PengaturanProfilRoute
  '/pengaturan/staf': typeof PengaturanStafRoute
  '/pengaturan/whatsapp': typeof PengaturanWhatsappRoute
  '/stok/bahan-baku': typeof StokBahanBakuRoute
  '/stok/kemasan': typeof StokKemasanRoute
  '/stok/pindah-wadah': typeof StokPindahWadahRoute
  '/api/cron/send-resi': typeof ApiCronSendResiRoute
  '/api/cron/sync-meta-ads': typeof ApiCronSyncMetaAdsRoute
  '/api/meta/reply-all-unreplied': typeof ApiMetaReplyAllUnrepliedRoute
  '/api/meta/reply-comment': typeof ApiMetaReplyCommentRoute
  '/api/meta/subscribe-page': typeof ApiMetaSubscribePageRoute
  '/api/meta/sync-comments': typeof ApiMetaSyncCommentsRoute
  '/api/webhooks/meta-comments': typeof ApiWebhooksMetaCommentsRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/import-riwayat': typeof ImportRiwayatRoute
  '/keuangan': typeof KeuanganRoute
  '/meta-ads': typeof MetaAdsRoute
  '/meta-comments': typeof MetaCommentsRoute
  '/pengeluaran': typeof PengeluaranRoute
  '/pengeluaran-pribadi': typeof PengeluaranPribadiRoute
  '/penjualan': typeof PenjualanRoute
  '/retur': typeof ReturRoute
  '/whatsapp-ai': typeof WhatsappAiRoute
  '/api/telegram-webhook': typeof ApiTelegramWebhookRoute
  '/api/waha-proxy': typeof ApiWahaProxyRoute
  '/pengaturan/harga': typeof PengaturanHargaRoute
  '/pengaturan/lumpsum': typeof PengaturanLumpsumRoute
  '/pengaturan/profil': typeof PengaturanProfilRoute
  '/pengaturan/staf': typeof PengaturanStafRoute
  '/pengaturan/whatsapp': typeof PengaturanWhatsappRoute
  '/stok/bahan-baku': typeof StokBahanBakuRoute
  '/stok/kemasan': typeof StokKemasanRoute
  '/stok/pindah-wadah': typeof StokPindahWadahRoute
  '/api/cron/send-resi': typeof ApiCronSendResiRoute
  '/api/cron/sync-meta-ads': typeof ApiCronSyncMetaAdsRoute
  '/api/meta/reply-all-unreplied': typeof ApiMetaReplyAllUnrepliedRoute
  '/api/meta/reply-comment': typeof ApiMetaReplyCommentRoute
  '/api/meta/subscribe-page': typeof ApiMetaSubscribePageRoute
  '/api/meta/sync-comments': typeof ApiMetaSyncCommentsRoute
  '/api/webhooks/meta-comments': typeof ApiWebhooksMetaCommentsRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/import-riwayat': typeof ImportRiwayatRoute
  '/keuangan': typeof KeuanganRoute
  '/meta-ads': typeof MetaAdsRoute
  '/meta-comments': typeof MetaCommentsRoute
  '/pengeluaran': typeof PengeluaranRoute
  '/pengeluaran-pribadi': typeof PengeluaranPribadiRoute
  '/penjualan': typeof PenjualanRoute
  '/retur': typeof ReturRoute
  '/whatsapp-ai': typeof WhatsappAiRoute
  '/api/telegram-webhook': typeof ApiTelegramWebhookRoute
  '/api/waha-proxy': typeof ApiWahaProxyRoute
  '/pengaturan/harga': typeof PengaturanHargaRoute
  '/pengaturan/lumpsum': typeof PengaturanLumpsumRoute
  '/pengaturan/profil': typeof PengaturanProfilRoute
  '/pengaturan/staf': typeof PengaturanStafRoute
  '/pengaturan/whatsapp': typeof PengaturanWhatsappRoute
  '/stok/bahan-baku': typeof StokBahanBakuRoute
  '/stok/kemasan': typeof StokKemasanRoute
  '/stok/pindah-wadah': typeof StokPindahWadahRoute
  '/api/cron/send-resi': typeof ApiCronSendResiRoute
  '/api/cron/sync-meta-ads': typeof ApiCronSyncMetaAdsRoute
  '/api/meta/reply-all-unreplied': typeof ApiMetaReplyAllUnrepliedRoute
  '/api/meta/reply-comment': typeof ApiMetaReplyCommentRoute
  '/api/meta/subscribe-page': typeof ApiMetaSubscribePageRoute
  '/api/meta/sync-comments': typeof ApiMetaSyncCommentsRoute
  '/api/webhooks/meta-comments': typeof ApiWebhooksMetaCommentsRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/import-riwayat'
    | '/keuangan'
    | '/meta-ads'
    | '/meta-comments'
    | '/pengeluaran'
    | '/pengeluaran-pribadi'
    | '/penjualan'
    | '/retur'
    | '/whatsapp-ai'
    | '/api/telegram-webhook'
    | '/api/waha-proxy'
    | '/pengaturan/harga'
    | '/pengaturan/lumpsum'
    | '/pengaturan/profil'
    | '/pengaturan/staf'
    | '/pengaturan/whatsapp'
    | '/stok/bahan-baku'
    | '/stok/kemasan'
    | '/stok/pindah-wadah'
    | '/api/cron/send-resi'
    | '/api/cron/sync-meta-ads'
    | '/api/meta/reply-all-unreplied'
    | '/api/meta/reply-comment'
    | '/api/meta/subscribe-page'
    | '/api/meta/sync-comments'
    | '/api/webhooks/meta-comments'
    | '/api/webhooks/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/import-riwayat'
    | '/keuangan'
    | '/meta-ads'
    | '/meta-comments'
    | '/pengeluaran'
    | '/pengeluaran-pribadi'
    | '/penjualan'
    | '/retur'
    | '/whatsapp-ai'
    | '/api/telegram-webhook'
    | '/api/waha-proxy'
    | '/pengaturan/harga'
    | '/pengaturan/lumpsum'
    | '/pengaturan/profil'
    | '/pengaturan/staf'
    | '/pengaturan/whatsapp'
    | '/stok/bahan-baku'
    | '/stok/kemasan'
    | '/stok/pindah-wadah'
    | '/api/cron/send-resi'
    | '/api/cron/sync-meta-ads'
    | '/api/meta/reply-all-unreplied'
    | '/api/meta/reply-comment'
    | '/api/meta/subscribe-page'
    | '/api/meta/sync-comments'
    | '/api/webhooks/meta-comments'
    | '/api/webhooks/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/import-riwayat'
    | '/keuangan'
    | '/meta-ads'
    | '/meta-comments'
    | '/pengeluaran'
    | '/pengeluaran-pribadi'
    | '/penjualan'
    | '/retur'
    | '/whatsapp-ai'
    | '/api/telegram-webhook'
    | '/api/waha-proxy'
    | '/pengaturan/harga'
    | '/pengaturan/lumpsum'
    | '/pengaturan/profil'
    | '/pengaturan/staf'
    | '/pengaturan/whatsapp'
    | '/stok/bahan-baku'
    | '/stok/kemasan'
    | '/stok/pindah-wadah'
    | '/api/cron/send-resi'
    | '/api/cron/sync-meta-ads'
    | '/api/meta/reply-all-unreplied'
    | '/api/meta/reply-comment'
    | '/api/meta/subscribe-page'
    | '/api/meta/sync-comments'
    | '/api/webhooks/meta-comments'
    | '/api/webhooks/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ImportRiwayatRoute: typeof ImportRiwayatRoute
  KeuanganRoute: typeof KeuanganRoute
  MetaAdsRoute: typeof MetaAdsRoute
  MetaCommentsRoute: typeof MetaCommentsRoute
  PengeluaranRoute: typeof PengeluaranRoute
  PengeluaranPribadiRoute: typeof PengeluaranPribadiRoute
  PenjualanRoute: typeof PenjualanRoute
  ReturRoute: typeof ReturRoute
  WhatsappAiRoute: typeof WhatsappAiRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  ApiWahaProxyRoute: typeof ApiWahaProxyRoute
  PengaturanHargaRoute: typeof PengaturanHargaRoute
  PengaturanLumpsumRoute: typeof PengaturanLumpsumRoute
  PengaturanProfilRoute: typeof PengaturanProfilRoute
  PengaturanStafRoute: typeof PengaturanStafRoute
  PengaturanWhatsappRoute: typeof PengaturanWhatsappRoute
  StokBahanBakuRoute: typeof StokBahanBakuRoute
  StokKemasanRoute: typeof StokKemasanRoute
  StokPindahWadahRoute: typeof StokPindahWadahRoute
  ApiCronSendResiRoute: typeof ApiCronSendResiRoute
  ApiCronSyncMetaAdsRoute: typeof ApiCronSyncMetaAdsRoute
  ApiMetaReplyAllUnrepliedRoute: typeof ApiMetaReplyAllUnrepliedRoute
  ApiMetaReplyCommentRoute: typeof ApiMetaReplyCommentRoute
  ApiMetaSubscribePageRoute: typeof ApiMetaSubscribePageRoute
  ApiMetaSyncCommentsRoute: typeof ApiMetaSyncCommentsRoute
  ApiWebhooksMetaCommentsRoute: typeof ApiWebhooksMetaCommentsRoute
  ApiWebhooksWhatsappRoute: typeof ApiWebhooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp-ai': {
      id: '/whatsapp-ai'
      path: '/whatsapp-ai'
      fullPath: '/whatsapp-ai'
      preLoaderRoute: typeof WhatsappAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retur': {
      id: '/retur'
      path: '/retur'
      fullPath: '/retur'
      preLoaderRoute: typeof ReturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penjualan': {
      id: '/penjualan'
      path: '/penjualan'
      fullPath: '/penjualan'
      preLoaderRoute: typeof PenjualanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengeluaran-pribadi': {
      id: '/pengeluaran-pribadi'
      path: '/pengeluaran-pribadi'
      fullPath: '/pengeluaran-pribadi'
      preLoaderRoute: typeof PengeluaranPribadiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengeluaran': {
      id: '/pengeluaran'
      path: '/pengeluaran'
      fullPath: '/pengeluaran'
      preLoaderRoute: typeof PengeluaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-comments': {
      id: '/meta-comments'
      path: '/meta-comments'
      fullPath: '/meta-comments'
      preLoaderRoute: typeof MetaCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-ads': {
      id: '/meta-ads'
      path: '/meta-ads'
      fullPath: '/meta-ads'
      preLoaderRoute: typeof MetaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan': {
      id: '/keuangan'
      path: '/keuangan'
      fullPath: '/keuangan'
      preLoaderRoute: typeof KeuanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-riwayat': {
      id: '/import-riwayat'
      path: '/import-riwayat'
      fullPath: '/import-riwayat'
      preLoaderRoute: typeof ImportRiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stok/pindah-wadah': {
      id: '/stok/pindah-wadah'
      path: '/stok/pindah-wadah'
      fullPath: '/stok/pindah-wadah'
      preLoaderRoute: typeof StokPindahWadahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stok/kemasan': {
      id: '/stok/kemasan'
      path: '/stok/kemasan'
      fullPath: '/stok/kemasan'
      preLoaderRoute: typeof StokKemasanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stok/bahan-baku': {
      id: '/stok/bahan-baku'
      path: '/stok/bahan-baku'
      fullPath: '/stok/bahan-baku'
      preLoaderRoute: typeof StokBahanBakuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/whatsapp': {
      id: '/pengaturan/whatsapp'
      path: '/pengaturan/whatsapp'
      fullPath: '/pengaturan/whatsapp'
      preLoaderRoute: typeof PengaturanWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/staf': {
      id: '/pengaturan/staf'
      path: '/pengaturan/staf'
      fullPath: '/pengaturan/staf'
      preLoaderRoute: typeof PengaturanStafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/profil': {
      id: '/pengaturan/profil'
      path: '/pengaturan/profil'
      fullPath: '/pengaturan/profil'
      preLoaderRoute: typeof PengaturanProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/lumpsum': {
      id: '/pengaturan/lumpsum'
      path: '/pengaturan/lumpsum'
      fullPath: '/pengaturan/lumpsum'
      preLoaderRoute: typeof PengaturanLumpsumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/harga': {
      id: '/pengaturan/harga'
      path: '/pengaturan/harga'
      fullPath: '/pengaturan/harga'
      preLoaderRoute: typeof PengaturanHargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waha-proxy': {
      id: '/api/waha-proxy'
      path: '/api/waha-proxy'
      fullPath: '/api/waha-proxy'
      preLoaderRoute: typeof ApiWahaProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram-webhook': {
      id: '/api/telegram-webhook'
      path: '/api/telegram-webhook'
      fullPath: '/api/telegram-webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/whatsapp': {
      id: '/api/webhooks/whatsapp'
      path: '/api/webhooks/whatsapp'
      fullPath: '/api/webhooks/whatsapp'
      preLoaderRoute: typeof ApiWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/meta-comments': {
      id: '/api/webhooks/meta-comments'
      path: '/api/webhooks/meta-comments'
      fullPath: '/api/webhooks/meta-comments'
      preLoaderRoute: typeof ApiWebhooksMetaCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/sync-comments': {
      id: '/api/meta/sync-comments'
      path: '/api/meta/sync-comments'
      fullPath: '/api/meta/sync-comments'
      preLoaderRoute: typeof ApiMetaSyncCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/subscribe-page': {
      id: '/api/meta/subscribe-page'
      path: '/api/meta/subscribe-page'
      fullPath: '/api/meta/subscribe-page'
      preLoaderRoute: typeof ApiMetaSubscribePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/reply-comment': {
      id: '/api/meta/reply-comment'
      path: '/api/meta/reply-comment'
      fullPath: '/api/meta/reply-comment'
      preLoaderRoute: typeof ApiMetaReplyCommentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/reply-all-unreplied': {
      id: '/api/meta/reply-all-unreplied'
      path: '/api/meta/reply-all-unreplied'
      fullPath: '/api/meta/reply-all-unreplied'
      preLoaderRoute: typeof ApiMetaReplyAllUnrepliedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-meta-ads': {
      id: '/api/cron/sync-meta-ads'
      path: '/api/cron/sync-meta-ads'
      fullPath: '/api/cron/sync-meta-ads'
      preLoaderRoute: typeof ApiCronSyncMetaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/send-resi': {
      id: '/api/cron/send-resi'
      path: '/api/cron/send-resi'
      fullPath: '/api/cron/send-resi'
      preLoaderRoute: typeof ApiCronSendResiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ImportRiwayatRoute: ImportRiwayatRoute,
  KeuanganRoute: KeuanganRoute,
  MetaAdsRoute: MetaAdsRoute,
  MetaCommentsRoute: MetaCommentsRoute,
  PengeluaranRoute: PengeluaranRoute,
  PengeluaranPribadiRoute: PengeluaranPribadiRoute,
  PenjualanRoute: PenjualanRoute,
  ReturRoute: ReturRoute,
  WhatsappAiRoute: WhatsappAiRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  ApiWahaProxyRoute: ApiWahaProxyRoute,
  PengaturanHargaRoute: PengaturanHargaRoute,
  PengaturanLumpsumRoute: PengaturanLumpsumRoute,
  PengaturanProfilRoute: PengaturanProfilRoute,
  PengaturanStafRoute: PengaturanStafRoute,
  PengaturanWhatsappRoute: PengaturanWhatsappRoute,
  StokBahanBakuRoute: StokBahanBakuRoute,
  StokKemasanRoute: StokKemasanRoute,
  StokPindahWadahRoute: StokPindahWadahRoute,
  ApiCronSendResiRoute: ApiCronSendResiRoute,
  ApiCronSyncMetaAdsRoute: ApiCronSyncMetaAdsRoute,
  ApiMetaReplyAllUnrepliedRoute: ApiMetaReplyAllUnrepliedRoute,
  ApiMetaReplyCommentRoute: ApiMetaReplyCommentRoute,
  ApiMetaSubscribePageRoute: ApiMetaSubscribePageRoute,
  ApiMetaSyncCommentsRoute: ApiMetaSyncCommentsRoute,
  ApiWebhooksMetaCommentsRoute: ApiWebhooksMetaCommentsRoute,
  ApiWebhooksWhatsappRoute: ApiWebhooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
